package routes

import (
	"devtools/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterHouseholdRoutes(api *gin.RouterGroup, h *RouteHandlers, createRateLimiter *middleware.RateLimiter) {
	household := api.Group("/household")
	{
		household.POST("/init", h.HouseholdHandler.Init)
		household.GET("/items", h.HouseholdHandler.GetItems)
		household.POST("/items", h.HouseholdHandler.CreateItem)
		household.GET("/items/:id", h.HouseholdHandler.GetItem)
		household.PUT("/items/:id", h.HouseholdHandler.UpdateItem)
		household.DELETE("/items/:id", h.HouseholdHandler.DeleteItem)
		household.POST("/items/:id/use", h.HouseholdHandler.UseItem)
		household.POST("/items/:id/restock", h.HouseholdHandler.RestockItem)
		household.POST("/items/:id/open", h.HouseholdHandler.OpenItem)
		household.GET("/templates", h.HouseholdHandler.GetTemplates)
		household.POST("/templates", h.HouseholdHandler.CreateTemplate)
		household.DELETE("/templates/:id", h.HouseholdHandler.DeleteTemplate)
		household.GET("/notifications", h.HouseholdHandler.GetNotifications)
		household.POST("/notifications/:id/read", h.HouseholdHandler.MarkNotificationAsRead)
		household.POST("/notifications/read-all", h.HouseholdHandler.MarkAllNotificationsAsRead)
		household.GET("/todos", h.HouseholdHandler.GetTodos)
		household.POST("/todos", h.HouseholdHandler.CreateTodo)
		household.PUT("/todos/:id", h.HouseholdHandler.UpdateTodo)
		household.DELETE("/todos/:id", h.HouseholdHandler.DeleteTodo)
		household.GET("/stats", h.HouseholdHandler.GetStats)
		household.GET("/ai/check", h.HouseholdHandler.AIFeatureCheck)
		household.POST("/ai/analyze", h.HouseholdHandler.AIAnalyze)
		household.POST("/ai/add", h.HouseholdHandler.AIAddItem)
		household.POST("/ai/parse", h.HouseholdHandler.AIParseItems)
		household.POST("/ai/todos/merge", h.HouseholdHandler.AIMergeTodos)
		household.GET("/ai/restock", h.HouseholdHandler.AISuggestRestock)
		household.POST("/chat", h.HouseholdHandler.Chat)
		household.GET("/chat/history", h.HouseholdHandler.GetChatHistory)
		household.DELETE("/chat/history", h.HouseholdHandler.ClearChatHistory)
		household.POST("/barcode/lookup", h.HouseholdHandler.BarcodeLookup)
		household.POST("/ocr/receipt", h.HouseholdHandler.ReceiptOCR)
		household.POST("/profile", h.HouseholdHandler.CreateProfile)
		household.POST("/profile/login", h.HouseholdHandler.LoginProfile)
		household.GET("/profile/:id", h.HouseholdHandler.GetProfile)
		household.PUT("/profile/:id/extend", h.HouseholdHandler.ExtendProfile)
		household.DELETE("/profile/:id", h.HouseholdHandler.DeleteProfile)
		household.POST("/profile/:id/items", h.HouseholdHandler.CreateProfileItem)
		household.GET("/profile/:id/items", h.HouseholdHandler.GetProfileItems)
		household.GET("/profile/:id/locations", h.HouseholdHandler.GetProfileLocations)
		household.GET("/profile/:id/locations/library", h.HouseholdHandler.GetLocationLibrary)
		household.POST("/profile/:id/locations/library", h.HouseholdHandler.CreateLocation)
		household.PUT("/profile/:id/locations/library/:locId", h.HouseholdHandler.UpdateLocation)
		household.DELETE("/profile/:id/locations/library/:locId", h.HouseholdHandler.DeleteLocation)
		household.GET("/profile/:id/space", h.HouseholdHandler.GetSpaceLayout)
		household.POST("/profile/:id/space", h.HouseholdHandler.SaveSpaceLayout)
		household.POST("/profile/:id/space/share", h.HouseholdHandler.CreateSpaceShare)
		household.GET("/space/share/:shareId", h.HouseholdHandler.GetSpaceShare)
		household.PUT("/profile/:id/items/:itemId", h.HouseholdHandler.UpdateProfileItem)
		household.DELETE("/profile/:id/items/:itemId", h.HouseholdHandler.DeleteProfileItem)
		household.POST("/profile/:id/items/:itemId/use", h.HouseholdHandler.UseProfileItem)
		household.POST("/profile/:id/items/:itemId/restock", h.HouseholdHandler.RestockProfileItem)
		household.POST("/profile/:id/items/:itemId/open", h.HouseholdHandler.OpenProfileItem)
	}
}
